namespace ChessTracking.Core.ImageProcessing.PipelineData;

/// <summary>
/// Data generated by chessboard detection
/// </summary>
public class ChessboardTrackingData
{
    public double FieldSize { get; set; }
}
